config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :lab_reports
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lab_report.rb
class LabReport < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 250 }
  validates :description, presence: true, length: { maximum: 500 }
  enum grade: { A: 'A', B: 'B', C: 'C', D: 'D', E: 'E', FX: 'FX', F: 'F' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, email: true, length: { maximum: 100 }
  validates :first_name, presence: true, length: { maximum: 100 }
  validates :last_name, presence: true, length: { maximum: 150 }

  def formatted_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def require_login
    unless user_signed_in?
      flash[:error] = "You must be logged in to access this section"
      authenticate_user!
      # redirect_to new_user_session_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :first_name, :last_name])
  end

  def after_sign_out_path_for(resourse_or_scope)
    request.referrer
  end
end

app/controllers/lab_reports_controller.rb
class LabReportsController < ApplicationController
  before_action :set_lab_report, only: %i[ show edit update destroy ]

  # GET /lab_reports or /lab_reports.json
  def index
    @lab_reports = LabReport.all
  end

  # GET /lab_reports/1 or /lab_reports/1.json
  def show
    @lab_report = LabReport.find(params[:id])
  end

  # GET /lab_reports/new
  def new
    @lab_report = LabReport.new
  end

  # GET /lab_reports/1/edit
  # Used for setting grade
  def edit
    @lab_report = LabReport.find(params[:id])
  end

  # POST /lab_reports or /lab_reports.json
  def create
    @lab_report = LabReport.new(lab_report_params)

    respond_to do |format|
      if @lab_report.save
        format.html { redirect_to @lab_report, notice: 'Lab report was successfully created.' }
        format.json { render :show, status: :created, location: @lab_report }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lab_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lab_reports/1 or /lab_reports/1.json
  # Used for setting grade
  def update
    lab_report = LabReport.find(params[:id])
    respond_to do |format|
      if lab_report.update(params.require(:lab_report).permit(:grade))
        format.html { redirect_to lab_report, notice: 'Lab report was successfully updated.' }
        format.json { render :show, status: :ok, location: lab_report }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: lab_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lab_reports/1 or /lab_reports/1.json
  def destroy
    @lab_report.destroy
    respond_to do |format|
      format.html { redirect_to lab_reports_url, notice: 'Lab report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lab_report
      @lab_report = LabReport.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lab_report_params
      params.require(:lab_report).permit(:user_id, :title, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lab_reports_helper.rb
module LabReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/lab_reports/_form.html.erb
<style>
    textarea {
        width: 300px;
        min-height: 200px;
    }

    .field select {
        min-width: 308px;
        height: 30px;
    }

    .field input {
        min-width: 300px;
    }
</style>

<%= form_with(model: lab_report) do |form| %>
  <% if lab_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lab_report.errors.count, "error") %> prohibited this lab_report from being saved:</h2>

      <ul>
        <% lab_report.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, User.all, :id, :formatted_name %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit "Save" %>
  </div>
<% end %>

app/views/lab_reports/_mark_form.html.erb
<%= form_with(model: lab_report) do |form| %>
  <% if lab_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lab_report.errors.count, "error") %> prohibited this lab_report from being saved:</h2>

      <ul>
        <% lab_report.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" id="grade">
    <%= form.label :grade, 'Mark' %>
    <%= form.text_field :grade, pattern: "A|B|C|D|E|FX|F", title: 'Must be one of ECTS grades' %>
  </div>

  <div class="actions">
    <%= form.submit "Save" %>
  </div>
<% end %>

app/views/lab_reports/edit.html.erb
<%= render "devise/sessions/logout", user: @user %>

<h1>Add mark</h1>

<%= render 'mark_form', lab_report: @lab_report %>

<%= button_to 'Back', lab_reports_path, method: :get %>

app/views/lab_reports/index.html.erb
<style>
  .buttons {
      display: flex;
  }
  .button_to {
      display: inline-block;
      margin-right: 10px;
  }
  .mark {
      margin-right: 32px;
  }
  .logout {
      text-align: right;
  }
</style>

<%= render "devise/sessions/logout", user: @user %>
<h2>Lab Reports</h2>

<%= button_to 'Add report', new_lab_report_path, method: :get %>
<% if @lab_reports %>
  <% @lab_reports.each do |lab_report| %>
    <div class="report">
      <h3><%= lab_report.title %></h3>
      <span style="font-size: small; font-style: italic">
            User: <%= User.find(lab_report.user_id).first_name %>
        <%= User.find(lab_report.user_id).last_name %>
        (<%= User.find(lab_report.user_id).email %>)
      </span>
      <div><%= lab_report.description %></div>
      <br>
      <span class="buttons">
        <% if !lab_report.grade %>
          <%= button_to 'Add mark', edit_lab_report_path(lab_report), method: :get %>
        <% else %>
        <span class="mark">  Mark: <%= lab_report.grade %> </span>
        <% end %>
        <%= button_to 'Remove', lab_report, method: :delete, data: { confirm: 'Are you sure?' } %>
      </span>
    </div>
    <hr>
  <% end %>
<% end %>

app/views/lab_reports/new.html.erb
<%= render "devise/sessions/logout", user: @user %>

<h2>New Lab Report</h2>

<%= render 'form', lab_report: @lab_report %>

<%= button_to 'Back', lab_reports_path, method: :get %>

app/views/lab_reports/show.html.erb
<style>
    .buttons {
        display: flex;
    }
    .button_to {
        display: inline-block;
        margin-right: 10px;
    }
</style>
<%= render "devise/sessions/logout", user: @user %>

<p>
  <strong>Title:</strong>
  <%= @lab_report.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @lab_report.description %>
</p>

<% unless @lab_report.grade.nil? %>
<p>
    <strong>Grade:</strong>
    <%=  @lab_report.grade  %>
</p>
<% end %>

<span class="buttons">
  <%= button_to 'Ok', lab_reports_path, method: :get %>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SRSTrpoTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render "devise/sessions/logout", user: @user %>

<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }
</style>
<%= render "devise/sessions/logout", user: @user %>

<h2>Users</h2>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th style="min-width: 200px">First name</th>
      <th style="min-width: 200px">Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render "devise/sessions/logout", user: @user %>

<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<%= render "devise/sessions/logout", user: @user %>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>